version: "3.8"

services:
  
  mysqldb:
    image: mysql
    restart: always
    ports:
    - 3306:3306
    # env_file: ./.env
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      # - /etc/mysql:/etc/mysql
      # - ./mysql-files:/var/lib/mysql-files
      - mysql_config:/etc/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_USER: user
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: carna_db;

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./api/:/api
      - /api/node_modules
    depends_on:
      - mysqldb
    ports:
      - "3000:3000" 
    env_file: ./api/.env

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./client/:/client
      - /client/node_modules
    depends_on:
      - api
    ports:
      - "8080:8080"

volumes:
  mysql:
  mysql_config: